# @Author: Thibault PECH
# @Date:   2022-01-31 08:50:36
# @Last Modified by:   Thibault PECH
# @Last Modified time: 2022-01-31 15:29:10
# Version du moteur docker compose
version: "3.9"

# Les conteneurs à démarrer
services: 
  # Création du conteneur db
  thibaultp-db: 
    # Téléchargement de la dernière version de MySQL
    image: mysql:latest
    volumes:
      # Création du volume db_data, bindé à /var/lib/mysql
      - db_data:/var/lib/mysql
    # Liste des environements
    environment:
      # MDP MySQL
      MYSQL_ROOT_PASSWORD: rtlry
      # Nom de la base de données
      MYSQL_DATABASE: wordpress
      # Nom de l'utilisateur
      MYSQL_USER: wordpress
      # MDP de l'utilisateur
      MYSQL_PASSWORD: wordpress
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=false

  # Création du conteneur wordpress
  thibaultp-wordpress:
    depends_on:
      # Ajout d'une dépanneur au conteneur db
      - thibaultp-db
    # Téléchargement de la dernière version de wordpress
    image: wordpress:latest
    volumes:
      # Création du volume wordpress_data, bindé à /var/www/html
      - wordpress_data:/var/www/html
    ##ports:
      # Ecoute de wordpress sur thibaultp-
      ##- "80:80"
    environment:
      # Connection à la base de données
      WORDPRESS_DB_HOST: thibaultp-db:3306
      # Nom de l'utilisateur BDD
      WORDPRESS_DB_USER: wordpress
      # MDP de l'utilisateur BDD
      WORDPRESS_DB_PASSWORD: wordpress
      # Nom de la base de données
      WORDPRESS_DB_NAME: wordpress
    labels:
      - "traefik.http.routers.tpwp.rule=Host(`wp.traefik.me`)"
      - "traefik.http.routers.tpwp-tls.tls.domains[0].main=wp.traefik.me"
      - "traefik.http.routers.tpwp-tls.tls.domains[0].sans=wp-*.traefik.me"
      - "traefik.http.middlewares.tpwp-rl.ratelimit.average=2"
      - "traefik.http.middlewares.tpwp-rl.ratelimit.burst=2"
      - "traefik.http.routers.tpwp.middlewares=tpwp-rl@docker"
      - "traefik.http.routers.tpwp-tls.middlewares=tpwp-rl@docker"
    
    networks:
      - traefik-proxy

# Les volumes sont vides car on ne sauvegarde pas les données
volumes:
  db_data: 
  wordpress_data: 

networks:
  traefik-proxy:
    external: true